/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401re_rcc.h>
#include <stm32f401re_gpio.h>
#include <misc.h>
#include <stm32f401re_exti.h>
#include <system_stm32f4xx.h>
#include <stm32f401re_syscfg.h>

#define GPIO_PIN_SET		1
#define GPIO_PIN_RESET		0

#define LED_GPIO_PORT		GPIOA
#define LED_GPIO_PIN		GPIO_Pin_5
#define LED_GPIO_RCC		RCC_AHB1Periph_GPIOA

#define BUTTON_IT_GPIO_PORT	GPIOC
#define BUTTON_IT_GPIO_PIN		GPIO_Pin_13
#define BUTTON_IT_GPIO_RCC		RCC_AHB1Periph_GPIOC
#define SYSCFG_GPIO_RCC		RCC_APB2Periph_SYSCFG

volatile uint8_t statusOfButton = 0;

static void Led_Init(void);
static void Button_InitINT (void);
void EXTI15_10_IRQHandler(void);
static void Led_Control(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint8_t status);

int main(void)
{
	SystemCoreClockUpdate();
	Led_Init();
	Button_InitINT();

	while(1)
	{
		Led_Control(LED_GPIO_PORT, LED_GPIO_PIN, statusOfButton);
	}
}

static void Led_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;

	RCC_AHB1PeriphClockCmd(LED_GPIO_RCC, ENABLE);

	GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

	GPIO_Init(LED_GPIO_PORT, &GPIO_InitStructure);
}

static void Button_InitINT (void)
{
	GPIO_InitTypeDef GPIO_InitStructure;
	EXTI_InitTypeDef EXTI_InitStructure;
	NVIC_InitTypeDef NVIC_InitStructure;

	//Enable GPIOC
	RCC_AHB1PeriphClockCmd(BUTTON_IT_GPIO_RCC, ENABLE);

	//Configure PC13 Pin as input pull up
	GPIO_InitStructure.GPIO_Pin = BUTTON_IT_GPIO_PIN;
	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_Init(BUTTON_IT_GPIO_PORT, &GPIO_InitStructure);

	//Enable Clock Syscfg, Connect EXTI Line13 to PC13 Pin
	RCC_APB2PeriphClockCmd(SYSCFG_GPIO_RCC, ENABLE);
	SYSCFG_EXTILineConfig(EXTI_PortSourceGPIOC, EXTI_PinSource13);

	//Configure EXTI Line13
	EXTI_InitStructure.EXTI_Line = EXTI_Line13;
	EXTI_InitStructure.EXTI_Mode = EXTI_Mode_Interrupt;
	EXTI_InitStructure.EXTI_Trigger = EXTI_Trigger_Falling;
	EXTI_InitStructure.EXTI_LineCmd = ENABLE;
	EXTI_Init(&EXTI_InitStructure);

	//Enable and set EXTI Line13 Interrupt to the lowest priority
	NVIC_InitStructure.NVIC_IRQChannel = EXTI15_10_IRQn;
	NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0;
	NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
	NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
	NVIC_Init(&NVIC_InitStructure);
}

void EXTI15_10_IRQHandler(void)
{
	if(EXTI_GetFlagStatus(EXTI_Line13) == SET)
	{
		//Set value when have even from Interrupt
		statusOfButton = 1;
	}

	//Clear bit PR Exit Interrupt
	EXTI_ClearITPendingBit(EXTI_Line13);
}

static void Led_Control(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint8_t status)
{
	if (status == GPIO_PIN_SET)
	{
		GPIO_SetBits(GPIOx, GPIO_Pin);
	}
	else if (status == GPIO_PIN_RESET)
	{
		GPIO_ResetBits(GPIOx, GPIO_Pin);
	}
}


