/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401re_rcc.h>
#include <stm32f401re_gpio.h>
#include <stm32f401re_tim.h>

#define TIM_PERIOD			8399

static void TimPwm_Init(void);
static void LedControl_PWM(uint8_t dutyCycle);

int main(void)
{
	SystemCoreClockUpdate();
	TimPwm_Init();

	while(1)
	{
		for (uint8_t dutyCycle = 0; dutyCycle <= 100; dutyCycle += 10)
		{
			LedControl_PWM(dutyCycle);
		}

		        // Decrease brightness
		for (uint8_t dutyCycle = 100; dutyCycle >= 0; dutyCycle -= 10)
		{
			LedControl_PWM(dutyCycle);
		}
	}
}

static void TimPwm_Init(void)
{
	GPIO_InitTypeDef 			GPIO_InitStructure;
	TIM_TimeBaseInitTypeDef 	TIM_InitStructure;
	TIM_OCInitTypeDef			TIM_OCInitStructure;

	//GPIOA clocks enable
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOA, ENABLE);

	//Initializes GPIO Use Output Compare
	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;

	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF;

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

	GPIO_PinAFConfig(GPIOA, GPIO_PinSource11, GPIO_AF_TIM1);

	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_11;

	GPIO_Init(GPIOA, &GPIO_InitStructure);

	//Enable Timer1
	TIM_InitStructure.TIM_CounterMode = TIM_CounterMode_Up;

	TIM_InitStructure.TIM_Prescaler = 0;

	TIM_InitStructure.TIM_Period = TIM_PERIOD;

	TIM_InitStructure.TIM_ClockDivision = 0;

	TIM_InitStructure.TIM_RepetitionCounter = 0;

	TIM_TimeBaseInit(TIM1, &TIM_InitStructure);


	TIM_OCInitStructure.TIM_OCMode = TIM_OCMode_PWM2;

	TIM_OCInitStructure.TIM_OCNPolarity = TIM_OCNPolarity_High;

	TIM_OCInitStructure.TIM_Pulse = 0;

	TIM_OCInitStructure.TIM_OutputState = TIM_OutputState_Enable;

	TIM_OC4Init(TIM1, &TIM_OCInitStructure);

	TIM_Cmd(TIM1, ENABLE);

	TIM_CtrlPWMOutputs(TIM1, ENABLE);
}

static void LedControl_PWM(uint8_t dutyCycle)
{
	static uint32_t pulse_length = 0;

	if(dutyCycle >= 100) return;

	//calculate pulse_length
	pulse_length = ((TIM_PERIOD * dutyCycle) / 100);

	TIM_SetCompare4(TIM1, pulse_length);
}
