/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401re_gpio.h>
#include <stm32f401re_rcc.h>

//Private macro
#define GPIO_PIN_SET		1
#define GPIO_PIN_RESET		0

#define LED_GPIO_PORT		GPIOA
#define LED_GPIO_PIN		GPIO_Pin_5
#define LED_GPIO_RCC		RCC_AHB1Periph_GPIOA

#define BUTTON_GPIO_PORT	GPIOC
#define BUTTON_GPIO_PIN		GPIO_Pin_13
#define BUTTON_GPIO_RCC		RCC_AHB1Periph_GPIOC

static void Led_Init(void);
static void Button_Init(void);
static void Led_Control(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint8_t status);
static uint8_t Button_GetLogic(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin);
void delay_ms(uint32_t milisecond);

int main(void)
{
	Button_Init();
	Led_Init();

	while (1)
	{
	        // Check if the button is pressed
		if (Button_GetLogic(BUTTON_GPIO_PORT, BUTTON_GPIO_PIN) == GPIO_PIN_RESET)
	    {
	            // Delay for button debounce
			delay_ms(50);

	            // Check again to ensure the button is still pressed
	        if (Button_GetLogic(BUTTON_GPIO_PORT, BUTTON_GPIO_PIN) == GPIO_PIN_RESET)
	        {
	                // Toggle the LED state
	        	static uint8_t ledState = GPIO_PIN_RESET;
	            ledState = (ledState == GPIO_PIN_SET) ? GPIO_PIN_RESET : GPIO_PIN_SET;
	            Led_Control(LED_GPIO_PORT, LED_GPIO_PIN, ledState);

	                // Wait for button release
	            while (Button_GetLogic(BUTTON_GPIO_PORT, BUTTON_GPIO_PIN) == GPIO_PIN_RESET);

	                // Delay to avoid multiple toggles during one button press
	            delay_ms(100);
	         }
	    }
	}
}

static void Led_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;

	RCC_AHB1PeriphClockCmd(LED_GPIO_RCC, ENABLE);

	GPIO_InitStructure.GPIO_Pin = LED_GPIO_PIN;

	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

	GPIO_Init(LED_GPIO_PORT, &GPIO_InitStructure);
}

static void Button_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;

	RCC_AHB1PeriphClockCmd(BUTTON_GPIO_RCC, ENABLE);

	GPIO_InitStructure.GPIO_Pin = BUTTON_GPIO_PIN;

	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN;

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;

	GPIO_Init(BUTTON_GPIO_PORT, &GPIO_InitStructure);
}

static void Led_Control(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin, uint8_t status)
{
	if (status == GPIO_PIN_SET)
	{
		GPIO_SetBits(GPIOx, GPIO_Pin);
	}
	else if (status == GPIO_PIN_RESET)
	{
		GPIO_ResetBits(GPIOx, GPIO_Pin);
	}
}

static uint8_t Button_GetLogic(GPIO_TypeDef* GPIOx, uint16_t GPIO_Pin)
{
	return GPIO_ReadInputDataBit(GPIOx, GPIO_Pin);
}

void delay_ms (uint32_t milisecond)
{
	for(uint32_t i = 0; i < milisecond; i++ )
	{
		for (uint32_t j = 0; j < 5000; j++);
	}
}
