/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "buzzer.h"
#include "melody.h"

void delay_ms(uint32_t milisecond)
{
	for (uint32_t i = 0; i < milisecond; i++)
	{
		for (uint32_t j = 0; j < 5000; j++);
	}
}

int main(void)
{
    BuzzerControl_Init();

	for(;;)
	{
		BuzzerControl_SetMelody(pbeep);
		delay_ms(1000);
		BuzzerControl_SetMelody(0);
		delay_ms(1000);
	}
}

