/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401re_rcc.h>
#include <stm32f401re_gpio.h>
#include <stm32f401re_tim.h>

#define LED_GREEN_GPIO_PORT		GPIOA
#define LED_GREEN_GPIO_PIN		GPIO_Pin_5
#define LED_GREEN_GPIO_RCC		RCC_AHB1Periph_GPIOA

void Led_Init(void);
void TimeBasic_Init(void);
void delay_ms (uint32_t milisecond);

int main(void)
{
	SystemCoreClockUpdate();
	Led_Init();
	TimeBasic_Init();

	while(1)
	{
		GPIO_SetBits(LED_GREEN_GPIO_PORT, LED_GREEN_GPIO_PIN);
		delay_ms(1000);

		GPIO_ResetBits(LED_GREEN_GPIO_PORT, LED_GREEN_GPIO_PIN);
		delay_ms(1000);
	}
}

void Led_Init(void)
{
	GPIO_InitTypeDef GPIO_InitStructure;

	RCC_AHB1PeriphClockCmd(LED_GREEN_GPIO_RCC, ENABLE);

	GPIO_InitStructure.GPIO_Pin = LED_GREEN_GPIO_PIN;

	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;

	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;

	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;

	GPIO_Init(LED_GREEN_GPIO_PORT, &GPIO_InitStructure);
}

void TimeBasic_Init(void)
{
	TIM_TimeBaseInitTypeDef Timer_InitStructure;

	RCC_AHB1PeriphClockCmd(RCC_APB2Periph_TIM1, ENABLE);

	Timer_InitStructure.TIM_CounterMode = TIM_CounterMode_Up;

	Timer_InitStructure.TIM_Prescaler = 83;

	Timer_InitStructure.TIM_Period = 999;

	Timer_InitStructure.TIM_ClockDivision = TIM_CKD_DIV1;

	Timer_InitStructure.TIM_RepetitionCounter = 0;

	TIM_TimeBaseInit(TIM1, &Timer_InitStructure);
	TIM_Cmd(TIM1, ENABLE);
}

void delay_ms (uint32_t milisecond)
{
	for(uint32_t i = 0; i < milisecond; i++ )
	{
		for (uint32_t j = 0; j < 5000; j++);
	}
}
